Repository feder-observatory/stellarphot, pull requests merged in 2023-07, with the labels that each got.

#126 Update seeing profile functions
  stellarphot/visualization/seeing_profile_functions.py
Labels: refactor

#132 Fixed documentation for calculate_noise and fixed bad terminology
  stellarphot/differential_photometry/aij_rel_fluxes.py
  stellarphot/differential_photometry/tests/test_aij_rel_fluxes.py
  stellarphot/io/aij.py
  stellarphot/photometry.py
  stellarphot/tests/test_photometry.py
Labels: refactor

#130 Initial reorganization of code
  CHANGES.rst
  stellarphot/differential_photometry/__init__.py
  stellarphot/gui_tools/__init__.py
  stellarphot/gui_tools/comparison_functions.py
  stellarphot/gui_tools/fits_opener.py
  stellarphot/gui_tools/photometry_widget_functions.py
  stellarphot/gui_tools/seeing_profile_functions.py
  stellarphot/gui_tools/tests/__init__.py
  stellarphot/gui_tools/tests/test_seeing_profile.py
  stellarphot/io/tess.py
  stellarphot/notebooks/comp-star-plots.ipynb
  stellarphot/notebooks/comp-stars-template.ipynb
  stellarphot/notebooks/image-viewer-working-copy.ipynb
  stellarphot/notebooks/photometry/01-viewer-seeing-template.ipynb
  stellarphot/notebooks/photometry/02-comp-star-plotter-template.ipynb
  stellarphot/notebooks/photometry/03-photometry-template.ipynb
  stellarphot/notebooks/photometry/05-relative-flux-calculation-template.ipynb
  stellarphot/notebooks/photometry/06-transit-fit-template.ipynb
  stellarphot/notebooks/photometry/07-transit-fit-with-exotic.ipynb
  stellarphot/notebooks/photometry/get_apass_comp_mags.ipynb
  stellarphot/notebooks/photometry/transform-pared-back.ipynb
  stellarphot/plotting/__init__.py
  stellarphot/plotting/aij_plots.py
  stellarphot/plotting/multi_night_plots.py
  stellarphot/plotting/transit_plots.py
  stellarphot/utils/__init__.py
  stellarphot/utils/catalog_search.py
  stellarphot/utils/comparison_utils.py
  stellarphot/utils/magnitude_transforms.py
  stellarphot/utils/tests/__init__.py
  stellarphot/utils/tests/data/all_apass_ey_uma_sorted_ra_first_20.fits
  stellarphot/utils/tests/data/clipped_ey_uma_vsx.fits
  stellarphot/utils/tests/data/low_error_apass_ey_uma_sorted_ra_first_20.fits
  stellarphot/utils/tests/data/mag_transform.csv
  stellarphot/utils/tests/data/sample_wcs_ey_uma.fits
  stellarphot/utils/tests/data/unclipped_ey_uma_vsx.fits
  stellarphot/utils/tests/test_catalog_search.py
  stellarphot/utils/tests/test_magnitude_transforms.py
Labels: refactor

#125 Initial version of BaseEnhancedTable and PhotometryData added
  CHANGES.rst
  stellarphot/core.py
  stellarphot/photometry.py
  stellarphot/tests/test_core.py
Labels: New base/data classes

#135 New Catalog Class added (as well as listing code and new pytests)
  .rtd-environment.yml
  CHANGES.rst
  stellarphot/__init__.py
  stellarphot/core.py
  stellarphot/photometry.py
  stellarphot/source_detection.py
  stellarphot/tests/data/test_vsx_table.ecsv
  stellarphot/tests/test_core.py
  stellarphot/tests/test_photometry.py
  tox.ini
Labels: refactor

#137 AperturesData data structure added
  stellarphot/core.py
  stellarphot/tests/data/test_aperture_table.ecsv
  stellarphot/tests/test_core.py
Labels: refactor

#139 Fixed data classes to behave like Tables for slicing, etc.
  stellarphot/core.py
  stellarphot/tests/test_core.py
Labels: bug, New base/data classes, refactor

#140 Various improvements to Core data classes
  stellarphot/core.py
  stellarphot/notebooks/photometry/03-photometry-template.ipynb
  stellarphot/photometry/source_detection.py
  stellarphot/tests/test_core.py
Labels: bug, New base/data classes, refactor
