Repository feder-observatory/stellarphot, pull requests merged in 2023-08, with the labels that each got.

#147 Update minimum Python version
  setup.cfg
  tox.ini
Labels: refactor

#146 Add writer for AAVSO files
  stellarphot/io/__init__.py
  stellarphot/io/aavso.py
  stellarphot/io/aavso_submission_schema.yml
  stellarphot/io/tests/data/dy-her-aavso-test-data.csv
  stellarphot/io/tests/test_aavso.py
  stellarphot/notebooks/photometry/calculate_aavso_mags_draft.ipynb
Labels: refactor

#145 Implementation of `multi_image_photometry()` code in photometry.py
  CHANGES.rst
  stellarphot/core.py
  stellarphot/photometry/photometry.py
  stellarphot/photometry/source_detection.py
  stellarphot/photometry/tests/data/test_sources.csv
  stellarphot/photometry/tests/fake_image.py
  stellarphot/photometry/tests/test_detection.py
  stellarphot/photometry/tests/test_photometry.py
Labels: refactor

#151 Fixed Notebooks 1 to 3 to work with new photometry code and new data classes
  stellarphot/gui_tools/comparison_functions.py
  stellarphot/gui_tools/photometry_widget_functions.py
  stellarphot/gui_tools/seeing_profile_functions.py
  stellarphot/notebooks/photometry/02-comp-star-plotter-template.ipynb
  stellarphot/notebooks/photometry/03-photometry-template.ipynb
  stellarphot/photometry/photometry.py
Labels: photometry notebook, New base/data classes, refactor

#150 Added logging to photometry functions (and two other tweaks)
  stellarphot/photometry/photometry.py
Labels: refactor, Reimplement w/new classes

#163 Added a pydantic-validated Camera class and test.
  CHANGES.rst
  stellarphot/core.py
  stellarphot/tests/test_core.py
Labels: refactor
