Repository feder-observatory/stellarphot, pull requests merged in 2024-06, with the labels that each got.

#358 Update seeing profile/aperture settings notebook to use new infrastructure
  stellarphot/gui_tools/seeing_profile_functions.py
  stellarphot/gui_tools/tests/test_seeing_profile.py
  stellarphot/notebooks/jp_app_launcher_stellarphot.yaml
  stellarphot/notebooks/photometry/01-viewer-seeing-template.ipynb
  stellarphot/settings/custom_widgets.py
  stellarphot/settings/tests/test_custom_widgets.py
Labels: UI :vomiting_face:

#362 Add feature to UI generator
  stellarphot/settings/tests/test_views.py
  stellarphot/settings/views.py
Labels: UI :vomiting_face:

#366 Updated ruff and black precommit revs and added codespell to precommit.
  .pre-commit-config.yaml
  README.md
  ignore-words.txt
  pyproject.toml
  stellarphot/photometry/photometry.py
  stellarphot/photometry/tests/test_photometry.py
Labels: tests, linting

#367 Fixed spellings in autoui_widget_viewer.upynb and stellarphot/core.py
  autoui_widget_viewer.ipynb
  docs/stellarphot/settings.rst
  ignore-words.txt
  stellarphot/core.py
  stellarphot/differential_photometry/vsx_mags.py
  stellarphot/gui_tools/tests/test_comparison_functions.py
  stellarphot/io/aavso_submission_schema.yml
  stellarphot/notebooks/photometry/05-relative-flux-calculation-template.ipynb
  stellarphot/notebooks/photometry/06-transit-fit-template.ipynb
  stellarphot/notebooks/photometry/07-transit-fit-with-exotic.ipynb
  stellarphot/notebooks/photometry/calculate_aavso_mags_draft.ipynb
  stellarphot/notebooks/photometry/get_apass_comp_mags.ipynb
  stellarphot/photometry/photometry.py
  stellarphot/photometry/tests/fake_image.py
  stellarphot/photometry/tests/test_photometry.py
  stellarphot/photometry/tests/test_profiles.py
  stellarphot/settings/custom_widgets.py
  stellarphot/settings/tests/test_astropy_pydantic.py
  stellarphot/tests/test_core.py
  stellarphot/transit_fitting/core.py
  stellarphot/transit_fitting/gui.py
  stellarphot/utils/magnitude_transforms.py
Labels: linting

#370 Make name of field match snake case version of class name
  stellarphot/gui_tools/comparison_functions.py
  stellarphot/gui_tools/tests/test_comparison_functions.py
  stellarphot/photometry/photometry.py
  stellarphot/photometry/tests/test_photometry.py
  stellarphot/settings/models.py
  stellarphot/settings/tests/test_models.py
Labels: UI :vomiting_face:
