Repository feder-observatory/stellarphot, pull requests merged in 2024-05, with the labels that each got.

#322 Fix remaining open issues with ChooseOrMakeNew widget
  stellarphot/settings/custom_widgets.py
  stellarphot/settings/tests/test_custom_widgets.py
Labels: UI :vomiting_face:

#336 Added all-contributors block for bot to process to README.md
  .all-contributorsrc
  README.md
Labels: documentation

#356 Updating the README.md file
  README.md
Labels: documentation

#359 Disentangling file and console logging
  stellarphot/photometry/photometry.py
  stellarphot/photometry/tests/test_photometry.py
  stellarphot/settings/models.py
Labels: tests, UI :vomiting_face:
